package entity;
// Generated Jul 31, 2020 10:02:53 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * DiaDiem generated by hbm2java
 */
public class DiaDiem  implements java.io.Serializable {


     private int idDiaDiem;
     private String ten;
     private String diaChi;
     private int sucChua;
     private Set dsHoiNghis = new HashSet(0);

    public DiaDiem() {
    }

	
    public DiaDiem(int idDiaDiem, String ten, String diaChi, int sucChua) {
        this.idDiaDiem = idDiaDiem;
        this.ten = ten;
        this.diaChi = diaChi;
        this.sucChua = sucChua;
    }
    public DiaDiem(int idDiaDiem, String ten, String diaChi, int sucChua, Set dsHoiNghis) {
       this.idDiaDiem = idDiaDiem;
       this.ten = ten;
       this.diaChi = diaChi;
       this.sucChua = sucChua;
       this.dsHoiNghis = dsHoiNghis;
    }
   
    public int getIdDiaDiem() {
        return this.idDiaDiem;
    }
    
    public void setIdDiaDiem(int idDiaDiem) {
        this.idDiaDiem = idDiaDiem;
    }
    public String getTen() {
        return this.ten;
    }
    
    public void setTen(String ten) {
        this.ten = ten;
    }
    public String getDiaChi() {
        return this.diaChi;
    }
    
    public void setDiaChi(String diaChi) {
        this.diaChi = diaChi;
    }
    public int getSucChua() {
        return this.sucChua;
    }
    
    public void setSucChua(int sucChua) {
        this.sucChua = sucChua;
    }
    public Set getDsHoiNghis() {
        return this.dsHoiNghis;
    }
    
    public void setDsHoiNghis(Set dsHoiNghis) {
        this.dsHoiNghis = dsHoiNghis;
    }




}


