package entity;
// Generated Jul 31, 2020 10:02:53 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javafx.scene.control.Button;

/**
 * DsHoiNghi generated by hbm2java
 */
public class DsHoiNghi  implements java.io.Serializable {


     private int idHoiNghi;
     private DiaDiem diaDiem;
     private String tenHoiNghi;
     private String moTa;
     private String moTaChiTiet;
     private Date thoiGian;
     private Date thoiGianKt;
     private byte[] hinhAnh;
     private String tenDiaDiem;
     private String trangThai;
     Button button;
     private Set thamGiaHns = new HashSet(0);

    public DsHoiNghi() {
    }
    
    public DsHoiNghi(DiaDiem diaDiem, String tenHoiNghi, String moTa, String moTaChiTiet, Date thoiGian, Date kt, byte[] hinhAnh) {
        this.diaDiem = diaDiem;
        this.tenHoiNghi = tenHoiNghi;
        this.moTa = moTa;
        this.moTaChiTiet = moTaChiTiet;
        this.thoiGian = thoiGian;
        this.thoiGianKt = kt;
        this.hinhAnh = hinhAnh;
    }

	
    public DsHoiNghi(int idHoiNghi, DiaDiem diaDiem, String tenHoiNghi, String moTa, String moTaChiTiet, Date thoiGian, Date kt, byte[] hinhAnh) {
        this.idHoiNghi = idHoiNghi;
        this.diaDiem = diaDiem;
        this.tenHoiNghi = tenHoiNghi;
        this.moTa = moTa;
        this.moTaChiTiet = moTaChiTiet;
        this.thoiGian = thoiGian;
        this.thoiGianKt = kt;
        this.hinhAnh = hinhAnh;
    }
    public DsHoiNghi(int idHoiNghi, DiaDiem diaDiem, String tenHoiNghi, String moTa, String moTaChiTiet, Date thoiGian, Date thoiGianKt, byte[] hinhAnh, Set thamGiaHns) {
       this.idHoiNghi = idHoiNghi;
       this.diaDiem = diaDiem;
       this.tenHoiNghi = tenHoiNghi;
       this.moTa = moTa;
       this.moTaChiTiet = moTaChiTiet;
       this.thoiGian = thoiGian;
       this.thoiGianKt = thoiGianKt;
       this.hinhAnh = hinhAnh;
       this.thamGiaHns = thamGiaHns;
    }
   
    public int getIdHoiNghi() {
        return this.idHoiNghi;
    }
    
    public void setIdHoiNghi(int idHoiNghi) {
        this.idHoiNghi = idHoiNghi;
    }
    public DiaDiem getDiaDiem() {
        return this.diaDiem;
    }
    
    public void setDiaDiem(DiaDiem diaDiem) {
        this.diaDiem = diaDiem;
    }
    public String getTenHoiNghi() {
        return this.tenHoiNghi;
    }
    
    public void setTenHoiNghi(String tenHoiNghi) {
        this.tenHoiNghi = tenHoiNghi;
    }
    public String getMoTa() {
        return this.moTa;
    }
    
    public void setMoTa(String moTa) {
        this.moTa = moTa;
    }
    public String getMoTaChiTiet() {
        return this.moTaChiTiet;
    }
    
    public void setMoTaChiTiet(String moTaChiTiet) {
        this.moTaChiTiet = moTaChiTiet;
    }
    public Date getThoiGian() {
        return this.thoiGian;
    }
    
    public void setThoiGian(Date thoiGian) {
        this.thoiGian = thoiGian;
    }
    public Date getThoiGianKt() {
        return this.thoiGianKt;
    }
    
    public void setThoiGianKt(Date thoiGianKt) {
        this.thoiGianKt = thoiGianKt;
    }
    public byte[] getHinhAnh() {
        return this.hinhAnh;
    }
    
    public void setHinhAnh(byte[] hinhAnh) {
        this.hinhAnh = hinhAnh;
    }
    public Set getThamGiaHns() {
        return this.thamGiaHns;
    }
    
    public void setThamGiaHns(Set thamGiaHns) {
        this.thamGiaHns = thamGiaHns;
    }

    
    public void setTenDiaDiem(String ten) {
        this.tenDiaDiem = ten;
    }
    
    public void setTrangThai(String trangthai) {
        this.trangThai = trangthai;
    }
    
    public String getTenDiaDiem() {
        return this.tenDiaDiem;
    }
    
    public String getTrangThai() {
        return this.trangThai;
    }

    public Button getButton(){
        return this.button;
    }
    
    public void setButton(){
        this.button = new Button("Huỷ");
        this.button.setDisable(true);
    }

}


