package entity;
// Generated Jul 19, 2020 9:34:35 AM by Hibernate Tools 4.3.1



/**
 * HinhAnh generated by hbm2java
 */
public class HinhAnh  implements java.io.Serializable {


     private int idHinhAnh;
     private byte[] anh;

    public HinhAnh() {
    }

    public HinhAnh(int idHinhAnh, byte[] anh) {
       this.idHinhAnh = idHinhAnh;
       this.anh = anh;
    }
   
    public int getIdHinhAnh() {
        return this.idHinhAnh;
    }
    
    public void setIdHinhAnh(int idHinhAnh) {
        this.idHinhAnh = idHinhAnh;
    }
    public byte[] getAnh() {
        return this.anh;
    }
    
    public void setAnh(byte[] anh) {
        this.anh = anh;
    }




}


