package entity;
// Generated Jul 31, 2020 10:02:53 AM by Hibernate Tools 4.3.1



/**
 * ThamGiaHnId generated by hbm2java
 */
public class ThamGiaHnId  implements java.io.Serializable {


     private int idHoiNghi;
     private int idUser;

    public ThamGiaHnId() {
    }

    public ThamGiaHnId(int idHoiNghi, int idUser) {
       this.idHoiNghi = idHoiNghi;
       this.idUser = idUser;
    }
   
    public int getIdHoiNghi() {
        return this.idHoiNghi;
    }
    
    public void setIdHoiNghi(int idHoiNghi) {
        this.idHoiNghi = idHoiNghi;
    }
    public int getIdUser() {
        return this.idUser;
    }
    
    public void setIdUser(int idUser) {
        this.idUser = idUser;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ThamGiaHnId) ) return false;
		 ThamGiaHnId castOther = ( ThamGiaHnId ) other; 
         
		 return (this.getIdHoiNghi()==castOther.getIdHoiNghi())
 && (this.getIdUser()==castOther.getIdUser());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdHoiNghi();
         result = 37 * result + this.getIdUser();
         return result;
   }   


}


