package entity;
// Generated Jul 31, 2020 10:02:53 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javafx.scene.control.Button;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private int idUser;
     private String ten;
     private String username;
     private String password;
     private String email;
     private int isAdmin;
     private Integer isBan;
     String trangThai;
     Button button;
     private Set thamGiaHns = new HashSet(0);

    public User() {
    }
    
    public User(String ten, String username, String password, String email, int isAdmin, int isBan) {
        
        this.ten = ten;
        this.username = username;
        this.password = password;
        this.email = email;
        this.isAdmin = isAdmin;
        this.isBan = isBan;
    }

	
    public User(int idUser, String ten, String username, String password, String email, int isAdmin, int isBan) {
        this.idUser = idUser;
        this.ten = ten;
        this.username = username;
        this.password = password;
        this.email = email;
        this.isAdmin = isAdmin;
        this.isBan = isBan;
    }
    public User(int idUser, String ten, String username, String password, String email, int isAdmin, Integer isBan, Set thamGiaHns) {
       this.idUser = idUser;
       this.ten = ten;
       this.username = username;
       this.password = password;
       this.email = email;
       this.isAdmin = isAdmin;
       this.isBan = isBan;
       this.thamGiaHns = thamGiaHns;
    }
   
    public int getIdUser() {
        return this.idUser;
    }
    
    public void setIdUser(int idUser) {
        this.idUser = idUser;
    }
    public String getTen() {
        return this.ten;
    }
    
    public void setTen(String ten) {
        this.ten = ten;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public int getIsAdmin() {
        return this.isAdmin;
    }
    
    public void setIsAdmin(int isAdmin) {
        this.isAdmin = isAdmin;
    }
    public Integer getIsBan() {
        return this.isBan;
    }
    
    public void setIsBan(Integer isBan) {
        this.isBan = isBan;
    }
    public Set getThamGiaHns() {
        return this.thamGiaHns;
    }
    
    public void setThamGiaHns(Set thamGiaHns) {
        this.thamGiaHns = thamGiaHns;
    }
    
    public String getTrangThai(){
        return this.trangThai;
    }
    
    public void setTrangThai(){
        if(isBan == 0){
            this.trangThai = "Hoạt động";
        }
        else{
            this.trangThai = "Bị chặn";
        }
    }
    
    public Button getButton(){
        return this.button;
    }
    
    public void setButton(Button btn){
        this.button = btn;
    }

}


